# Workflow that runs on closed PRs to the default branch

name: Default Branch PR Merged CI (Python)

on:
  pull_request:
    types: ["closed"]
    branches: ["main"]

# Specify concurrency such that only one workflow can run at a time
# * Different workflow files are not affected
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false


jobs:

  # Define an autotagger job that creates tags on changes to master
  # Use #major #minor in merge commit messages to bump version beyond patch
  bump-tag:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merged == true
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true

      - name: Print tags
        env:
          OLD_TAG: ${{ steps.tag.outputs.tag }}
          NEW_TAG: ${{ steps.tag.outputs.new_tag }}
        run: echo "$OLD_TAG -> $NEW_TAG"

